ALTER TABLE consultancy_jobs DROP CONSTRAINT consultancy_jobs_status_check;
ALTER TABLE consultancy_jobs ADD CONSTRAINT consultancy_jobs_status_check CHECK (status IN ('requested','booked','active','completed','cancelled'));
ALTER TABLE client_profiles ADD COLUMN company text NOT NULL DEFAULT '' CHECK(length(company)<=200);
ALTER TABLE client_profiles ADD COLUMN phone text NOT NULL DEFAULT '' CHECK(length(phone)<=40);
CREATE TABLE owner_accounts(client_id uuid PRIMARY KEY REFERENCES client_profiles(id) ON DELETE CASCADE);
INSERT INTO owner_accounts SELECT DISTINCT client_id FROM portal_sessions WHERE roles ? 'owner' OR roles ? 'admin';
CREATE TABLE job_tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES consultancy_jobs(id) ON DELETE CASCADE,title text NOT NULL CHECK(length(title) BETWEEN 1 AND 200),completed boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX job_tasks_job ON job_tasks(job_id);
CREATE TABLE job_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES consultancy_jobs(id) ON DELETE CASCADE,status text NOT NULL,actor_id uuid REFERENCES client_profiles(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE portal_notifications ADD COLUMN read_at timestamptz;
CREATE TABLE push_subscriptions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),client_id uuid NOT NULL REFERENCES client_profiles(id) ON DELETE CASCADE,endpoint text NOT NULL UNIQUE,keys jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE push_deliveries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),notification_id uuid NOT NULL REFERENCES portal_notifications(id) ON DELETE CASCADE,subscription_id uuid NOT NULL REFERENCES push_subscriptions(id) ON DELETE CASCADE,attempts integer NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),delivered_at timestamptz,UNIQUE(notification_id,subscription_id));
CREATE INDEX push_pending ON push_deliveries(next_attempt_at) WHERE delivered_at IS NULL;
CREATE TABLE mail_sends(id uuid PRIMARY KEY,client_id uuid NOT NULL REFERENCES client_profiles(id) ON DELETE CASCADE,message_id text NOT NULL UNIQUE,payload_hash text NOT NULL,status text NOT NULL CHECK(status IN ('sending','sent','uncertain')),sent_copy boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE conversations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),client_id uuid NOT NULL UNIQUE REFERENCES client_profiles(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE conversation_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),sequence bigint GENERATED ALWAYS AS IDENTITY UNIQUE,conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,sender_id uuid NOT NULL REFERENCES client_profiles(id) ON DELETE CASCADE,body text NOT NULL CHECK(length(body) BETWEEN 1 AND 4000),client_nonce uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(sender_id,client_nonce));
CREATE INDEX conversation_messages_thread ON conversation_messages(conversation_id,sequence);
ALTER TABLE portal_notifications ALTER COLUMN job_id DROP NOT NULL;
ALTER TABLE portal_notifications ADD COLUMN conversation_id uuid REFERENCES conversations(id) ON DELETE CASCADE;
CREATE TABLE mail_watch(mailbox text PRIMARY KEY,uid_validity text NOT NULL,last_uid bigint NOT NULL);
