apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: webmail-certificate
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ingress
  to:
    - group: ''
      kind: Secret
      name: mail-tls
