className: ataimo-envoy
routes:
  - name: portfolio
    namespace: app
    hostname: ataimo.com
    service: portfolio
    port: 3000
  - name: keycloak
    namespace: identity
    hostname: keycloak.ataimo.com
    service: keycloak
    port: 8080
  - name: grafana
    namespace: monitoring
    hostname: grafana.ataimo.com
    service: monitoring-grafana
    port: 80
  - name: redpanda-console
    namespace: streaming
    hostname: redpanda.ataimo.com
    service: redpanda-console
    port: 8080
proxy:
  concurrency: 2
  deployment:
    replicas: 1
    container:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          memory: 256Mi
    patch:
      type: StrategicMerge
      value:
        spec:
          template:
            spec:
              containers:
                - name: envoy
                  startupProbe:
                    timeoutSeconds: 5
                    failureThreshold: 60
                  livenessProbe:
                    timeoutSeconds: 5
                    failureThreshold: 6
                  readinessProbe:
                    timeoutSeconds: 5
                - name: shutdown-manager
                  livenessProbe:
                    timeoutSeconds: 5
                    failureThreshold: 6
                  readinessProbe:
                    timeoutSeconds: 5
