{{- range $name, $values := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
stringData:
  {{- range $key, $value := $values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
